'use client'

import type { Metadata } from 'next'
import IconGallery from '@/components/IconGallery'
import { SampleDialog } from '@/components/SampleDialog'
import { SampleDropdown } from '@/components/SampleDropdown'
import { SampleNavigation } from '@/components/SampleNavigation'
import { AccordionItem, ExclusiveAccordion, ListItem } from '@reusable-ui/components'
import { UploadImage } from '@/components/UploadImage'



// cssfn:
import {
    // style sheets:
    dynamicStyleSheets,
}                           from '@cssfn/cssfn-react'
import './pageStyle'



// styles:
const useHomeStyleSheet = dynamicStyleSheets(
    () => import(/* webpackPrefetch: true */'./pageStyle')
, { id: 'uzr425g47q' }); // a unique salt for SSR support, ensures the server-side & client-side have the same generated class names
import './pageStyle'
import { SampleWysiwygEditor } from '@/components/SampleWysiwygEditor'
import MasterPage from '@/components/MasterPage/MasterPage'



// export const metadata: Metadata = {
//     title       : 'Create Next App',
//     description : 'Generated by create next app',
//     viewport    : 'width=device-width, initial-scale=1',
// }
export default function Home() {
    // styles:
    const styleSheets = useHomeStyleSheet();
    
    
    
    return (
        <MasterPage>
            <ExclusiveAccordion theme='primary'>
                <AccordionItem bodyComponent={<ListItem className={styleSheets.demoPanel} />} label={<code>{'<Dropdown>'}</code>}>
                    <SampleDropdown />
                </AccordionItem>
                <AccordionItem bodyComponent={<ListItem className={styleSheets.demoPanel} />} label={<code>{'<CustomDialog>'}</code>}>
                    <SampleDialog />
                </AccordionItem>
                <AccordionItem bodyComponent={<ListItem className={styleSheets.demoPanel} />} label={<code>{'<Navigation>'}</code>}>
                    <SampleNavigation />
                </AccordionItem>
                <AccordionItem bodyComponent={<ListItem className={styleSheets.demoPanel} />} label={<code>{'<Pagination>'}</code>}>
                    <IconGallery />
                </AccordionItem>
                <AccordionItem bodyComponent={<ListItem className={`${styleSheets.demoPanel} ${styleSheets.demoPanelUpload}`} />} label={<code>{'<UploadImage>'}</code>}>
                    <UploadImage />
                </AccordionItem>
                <AccordionItem bodyComponent={<ListItem className={`${styleSheets.demoPanel} ${styleSheets.demoPanelUpload}`} />} label={<code>{'<WysiwygEditor>'}</code>}>
                    <SampleWysiwygEditor />
                </AccordionItem>
            </ExclusiveAccordion>
        </MasterPage>
    )
}
