'use client'

import type { Metadata } from 'next'
import IconGallery from '@/components/IconGallery'
import { SampleDialog } from '@/components/SampleDialog'
import { SampleDropdown } from '@/components/SampleDropdown'
import { SampleNavigation } from '@/components/SampleNavigation'
import { AccordionItem, ExclusiveAccordion, ListItem } from '@reusable-ui/components'
import { UploadImage } from '@/components/UploadImage'



// cssfn:
import {
    // style sheets:
    dynamicStyleSheets,
}                           from '@cssfn/cssfn-react'
import './pageStyle'



// styles:
const usePageUploadImageStyleSheet = dynamicStyleSheets(
    () => import(/* webpackPrefetch: true */'./pageStyle')
, { id: 'i8p2obko1b' }); // a unique salt for SSR support, ensures the server-side & client-side have the same generated class names
import './pageStyle'
import { SampleWysiwygEditor } from '@/components/SampleWysiwygEditor'
import MasterPage from '@/components/MasterPage/MasterPage'



// export const metadata: Metadata = {
//     title       : 'Create Next App',
//     description : 'Generated by create next app',
//     viewport    : 'width=device-width, initial-scale=1',
// }
export default function PageUploadImage() {
    // styles:
    const styleSheets = usePageUploadImageStyleSheet();
    
    
    
    return (
        <MasterPage>
            <UploadImage />
        </MasterPage>
    )
}
